 spring:
  datasource:
    url: jdbc:mysql://localhost:3307/myapp_db
    username: admin
    password: password123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
app:
  datasource:
    url: jdbc:mysql://localhost:3307/myapp_db
    username: admin
    password: password123

server.port: 8085
management:
  endpoints:
    web:
      exposure:
        include: mappings



logging:
  level:
    org:
      springframework:
        transaction: DEBUG
        orm.jpa : DEBUG
      hibernate.orm.jdbc.bind: trace #This property will show the sql queries with binding parameters instead of ?